name: Release
on:
  push:
    branches:
      - sentry

permissions:
  contents: read # for checkout

jobs:
  build_release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to push Docker images to GitHub Packages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - name: yarn install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - name: Audit npm signatures
        run: npm audit signatures
      - name: Generate sourcemaps
        run: |
          cd server
          yarn install --frozen-lockfile
          yarn run build
#      - name: Build Docker image
#        run: docker build --tag gafirst/match-uploader:sentry-test -f Dockerfile .
      - name: Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_ORG: "gafirst"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: "match-uploader-backend"
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Create Sentry release (server)
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT_BACKEND }}
        with:
          environment: production
          sourcemaps: "./server/dist/"
          release: ${{ steps.release.outputs.new-release-version }}
          release_prefix: "v"
          dist: "${{ github.workflow }}-${{ github.run_number }}-${{ github.run_attempt }}-server"
          disable_telemetry: true
